name: BuyRegion
version: @version@
main: com.region.buyregion.BuyRegion
api-version: 1.13
depend: [Vault, WorldGuard]
authors: [GentleGravel, Luke199]
description: WorldGuard Region Sales
commands:
  buyregion:
    description: toggles region buy or rent mode.